### ISSUE TITLE
index.html not showing up

### ISSUE THREAD

**Issue by leninworld** [john-guerra/vastChallenge2017_example#1]
Hi, index.html is not showing up anything for me. Pls provide instructions. Thank you!

**Comment by john-guerra** [comment]
As with any demo that loads data asynchronously you need to run a http server to use it. Try

python -m SimpleHTTPServer 

or 

http-server

http://lmgtfy.com/?q=how+to+run+a+http+server

**Comment by leninworld** [comment]
Thank you for reply. I did that. But got below error in browser.

Uncaught RangeError: Maximum call stack size exceeded(…)
http://localhost:8080/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
dc.js:1631 Uncaught dc.errors.InvalidStateException
dc.js:1631 Uncaught dc.errors.InvalidStateException
dc.js:1631 Uncaught dc.errors.InvalidStateException
dc.js:1631 Uncaught dc.errors.InvalidStateException
dc.js:1631 Uncaught dc.e…s.InvalidStateException {message: "Mandatory attribute chart.dimension is missing on chart[#carType]", stack: "Error↵    at dc.errors.InvalidStateException.dc.er…challenge_1/dc.js:251:19)↵    at <anonymous>:1:20"}

**Comment by john-guerra** [comment]
That error appears when there are null values on the data... If you are using the example on the code it might be a Windows or browser issue, because the example uses a gziped file. I just tested it again on Mac with Chrome 59 and it works, try loading the slice

**Comment by john-guerra** [comment]
I just commited a new version that uses the smaller dataset. Try this one

**Comment by john-guerra** [comment]
Also check if this one works https://john-guerra.github.io/vastChallenge2017_example/minichallenge_1/

**Comment by leninworld** [comment]
Link "https://john-guerra.github.io/vastChallenge2017_example/minichallenge_1/" works

**Comment by leninworld** [comment]
Now it works with the latest code from github. Thank you!
